name: allervie-nextjs-dashboard
region: sfo
services:
  - name: web
    github:
      repo: jhillbht/allervie-nextjs-clone
      branch: main
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${api.INTERNAL_URL}
        scope: BUILD_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
  
  - name: api
    github:
      repo: jhillbht/allervie-fastapi-backend
      branch: main
    build_command: pip install -r requirements.txt
    run_command: python main.py
    http_port: 5002
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: ENVIRONMENT
        value: production
        scope: RUN_TIME
      - key: GOOGLE_CLIENT_ID
        value: 22083613754-d1omeg2958vrsndpqg2v1jp0ncm7sr23.apps.googleusercontent.com
        scope: RUN_TIME
      - key: GOOGLE_CLIENT_SECRET
        value: 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
        type: SECRET
        scope: RUN_TIME
      - key: SECRET_KEY
        value: allervie-dashboard-next-fastapi-secret-key-2025
        type: SECRET
        scope: RUN_TIME
      - key: CLIENT_CUSTOMER_ID
        value: 8127539892
        scope: RUN_TIME
