name: allervie-analytics-dashboard
services:
  - name: web
    github:
      repo: jhillbht/allervie-nextjs-clone
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${APP_URL}/api
