name: allervie-unified
region: nyc
services:
- name: api
  github:
    branch: google-ads-improvements
    repo: jhillbht/allervie-dashboard
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 5002
  routes:
  - path: /
    preserve_path_prefix: true
  health_check:
    http_path: /api/health
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: FLASK_APP
    value: app.py
  - key: FLASK_ENV
    value: production
  - key: ALLOW_MOCK_DATA
    value: "false" 
  - key: ALLOW_MOCK_AUTH
    value: "false"
  - key: ENVIRONMENT
    value: "production"
  - key: USE_REAL_ADS_CLIENT
    value: "true"
  - key: GOOGLE_ADS_CLIENT_ID
    value: "22083613754-d1omeg2958vrsndpqg2v1jp0ncm7sr23.apps.googleusercontent.com"
  - key: GOOGLE_ADS_CLIENT_SECRET
    type: SECRET
    value: "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"
  - key: GOOGLE_ADS_DEVELOPER_TOKEN
    type: SECRET
    value: "EkXFENjahSDnpNRZJhWAAw"
  - key: GOOGLE_ADS_LOGIN_CUSTOMER_ID
    value: "8127539892"
  - key: GOOGLE_ADS_REFRESH_TOKEN
    type: SECRET
    value: "1//0fd0hT4p-0f4nCgYIARAAGA8SNwF-L9IrExeEoV1QfhOWXSUZCc1I1j_RpHpQ1bJ_xlDCmcDSCZ103BiUsy1MAr6awvafzZ6sPTk"
  - key: GOOGLE_ADS_USE_PROTO_PLUS
    value: "true"
  - key: GOOGLE_ADS_API_VERSION
    value: "v17"
  - key: TOKEN_AUTO_REFRESH_ENABLED
    value: "true"
  - key: AUTO_REFRESH_INTERVAL_MINUTES
    value: "30"
  - key: CLIENT_CUSTOMER_ID
    value: "8127539892"
  - key: USE_ENHANCED_REFRESH
    value: "true"
  - key: APP_URL
    value: "allervie-unified.ondigitalocean.app"